import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {unzipSync,zipSync,strToU8} from 'fflate';
const require=createRequire(import.meta.url);
const appUrl=process.env.IKS_APP_URL;
test('chapter visual direction survives reopen and produces a separate reference request and panorama import',{skip:!appUrl,timeout:120000},async()=>{
 const {chromium}=require(process.env.IKS_PLAYWRIGHT_MODULE || 'playwright');
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${appUrl}/template-studio`);
  await page.getByText('Your books will appear here. Saved on this browser; download a ZIP for backup.',{exact:true}).waitFor();
  await page.locator('.children-gallery article').filter({hasText:'Razia Learns to Swim'}).getByRole('button',{name:'Use template',exact:true}).click();
  await page.getByLabel('Book title',{exact:true}).fill('One chapter test');
  await page.getByLabel('Reader age / audience',{exact:true}).fill('9–14');
  await page.getByLabel('Choose your PDF or DOCX').setInputFiles({name:'chapter.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:Buffer.from('Test chapter text')});
  await page.getByText('Visual direction (optional)',{exact:true}).click();
  await page.getByLabel('Recurring characters',{exact:true}).fill('A boy, a girl and Chanakya');
  await page.getByLabel('Illustration notes',{exact:true}).fill('Warm textured painting with consistent outfits');
  const buffer=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=120;c.height=80;c.getContext('2d').fillRect(0,0,120,80);return c.toDataURL().split(',')[1];}),'base64');
  await page.getByLabel('Add style references').setInputFiles({name:'style.png',mimeType:'image/png',buffer});
  await page.getByRole('button',{name:'Remove reference 1',exact:true}).waitFor();
  await page.getByRole('button',{name:'Save book now',exact:true}).click();
  await page.getByText('Saved in this browser',{exact:true}).waitFor();
  await page.reload();
  await page.getByRole('button',{name:'One chapter test · 0 spreads',exact:true}).click();
  assert.equal(await page.getByLabel('Reader age / audience',{exact:true}).inputValue(),'9–14');
  await page.getByText('Visual direction (optional)',{exact:true}).click();
  assert.equal(await page.locator('.ts-visual-direction textarea').first().inputValue(),'A boy, a girl and Chanakya');
  assert.equal(await page.locator('.ts-visual-direction img').count(),1);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download request ZIP',exact:true}).click();
  const entries=unzipSync(new Uint8Array(await readFile(await (await downloadPromise).path())));
  assert.equal(Object.keys(entries).filter(k=>k.startsWith('references/')).length,1);
  assert.equal(Object.keys(entries).filter(k=>k.startsWith('images/')).length,0);
  const prompt=new TextDecoder().decode(entries['START-HERE.txt']);
  assert.match(prompt,/9–14/);assert.match(prompt,/A boy, a girl and Chanakya/);
  const id=prompt.match(/"projectId": "([^"]+)"/)[1];
  const book={format:'iks-template-book-v1',projectId:id,templateId:'bedtime-skies',title:'One chapter test',language:'English',characterGuide:'Fixed trio',pages:[{id:'spread-01',title:'A lesson',original:'Test source text',meaning:'Hindi meaning\nEnglish translation\nChildren’s explanation',sourceReference:'Chapter 1',scene:'The trio observing nature',image:'spread-01.png',layout:'panorama',fontSize:22,imageScale:100}]};
  await page.getByLabel('Import ChatGPT’s ZIP or book.json').setInputFiles({name:'result.zip',mimeType:'application/zip',buffer:Buffer.from(zipSync({'book.json':strToU8(JSON.stringify(book)),'images/spread-01.png':buffer,'images/character-reference.png':buffer}))});
  await page.getByRole('heading',{name:'One chapter test',exact:true}).waitFor();
  assert.equal(await page.locator('.ts-editor aside button').count(),1);
  assert.equal(await page.locator('.ts-fields select').inputValue(),'panorama');
  const live=await page.locator('.ts-live').evaluate(el=>{const a=el.querySelector('.art').getBoundingClientRect(),c=el.querySelector('.copy').getBoundingClientRect();return {above:a.bottom<=c.top+1,bg:getComputedStyle(el.querySelector('.copy')).backgroundColor};});
  assert.equal(live.above,true);assert.equal(live.bg,'rgb(255, 255, 255)');
  await page.getByRole('button',{name:'Read book',exact:true}).click();
  const frame=page.frameLocator('iframe[title="Your assembled book"]');
  await frame.locator('.art img').waitFor();
  assert.equal(await frame.locator('.art img').count(),1);
  assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
