"use client";
import {useEffect,useState} from 'react';
import type {Edition} from '../../lib/devotional-edition';
import {artContext,artStatus,type ProductionAction} from '../../lib/art-production';
import {ReferencePicture} from './visual-reference-workspace';
export type ArtUpload={requestId:string;file:File;note:string;caption:string;credit:string;provenance:'uploaded'|'external-generation'};
export function ArtProductionWorkspace({edition,busy,onAction,onUpload,onPackage,onImage,onDirty}:{edition:Edition;busy:boolean;onAction:(a:ProductionAction)=>Promise<boolean>;onUpload:(a:ArtUpload)=>Promise<boolean>;onPackage:(id:string)=>Promise<void>;onImage:(key:string)=>Promise<Blob>;onDirty:(v:boolean)=>void}){
 const plans=edition.storyboard||[],production=edition.artProduction;
 const [planId,setPlanId]=useState(plans[0]?.id||''),[note,setNote]=useState(''),[requestId,setRequestId]=useState(''),[file,setFile]=useState<File|null>(null),[credit,setCredit]=useState(''),[caption,setCaption]=useState(''),[revision,setRevision]=useState(''),[origin,setOrigin]=useState<ArtUpload['provenance']>('uploaded');
 const [left,setLeft]=useState(''),[right,setRight]=useState('');
 const dirty=!!note||!!file||!!credit||!!caption||!!revision;
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 const requests=production?.requests.filter(r=>r.planId===planId)||[],request=requests.find(r=>r.id===requestId)||requests.at(-1),art=production?.spreads.find(s=>s.planId===planId);
 const all=production?.spreads.flatMap(s=>s.versions.map(v=>({...v,planId:s.planId})))||[];
 const a=all.find(v=>v.id===left)||art?.versions.find(v=>v.id===art.approvedId)||art?.versions[0],b=all.find(v=>v.id===right)||art?.versions.at(-1);
 function clear(){setNote('');setFile(null);setCredit('');setCaption('');setRevision('');}
 if(!plans.length)return <section className="edition-panel"><h1>Artwork production</h1><p>Create a storyboard plan before producing artwork.</p></section>;
 return <section className="production-workspace"><header className="edition-panel"><h1>Artwork production</h1><p>Save the production brief, import finished artwork, compare revisions, and select the approved version. Imports never replace approved art automatically.</p><label>Spread<select disabled={busy||dirty} value={planId} onChange={e=>{setPlanId(e.target.value);setRequestId('');setLeft('');setRight('');}}>{plans.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><p>{artStatus(edition,planId)}</p><p>In-app generation is disabled. No paid service is called. You can use a request package with an external illustrator or image tool.</p></header>
 <div className="production-columns"><section className="edition-panel"><h2>Production request</h2><fieldset disabled={busy}><label>Production or revision direction<textarea value={note} maxLength={4000} onChange={e=>setNote(e.target.value)} placeholder="Describe the scene or changes while preserving the approved identity"/></label><button disabled={!note.trim()||!!file} onClick={()=>void(async()=>{if(await onAction({type:'create-art-request',planId,note})){setNote('');setRequestId('');}})()}>Save production request</button><label>Saved request<select value={request?.id||''} onChange={e=>setRequestId(e.target.value)} disabled={!!file}>{requests.map((r,i)=><option key={r.id} value={r.id}>Request {i+1} — {r.note.slice(0,80)}</option>)}</select></label>{request&&<><p>Print target: {request.width} × {request.height} pixels at 300 dpi including bleed.</p>{request.context!==artContext(edition,planId)&&<p className="edition-error">Upstream direction changed since this request. Its original inputs remain preserved. Create a new request for revised work, or review an imported result against the current direction before approval.</p>}<button onClick={()=>void onPackage(request.id)}>Download production ZIP</button><details><summary>Saved production brief</summary><pre className="production-brief">{request.prompt}</pre></details></>}</fieldset></section>
 <section className="edition-panel"><h2>Import finished artwork</h2><p>PNG, JPEG, or WebP up to 10 MB and 64 megapixels. A failed upload retains the request and your form so you can retry.</p><fieldset disabled={busy||!request}><label>Artwork file<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);e.currentTarget.value='';}}/></label>{file&&<p>{file.name}</p>}<label>Revision note<textarea value={revision} maxLength={4000} onChange={e=>setRevision(e.target.value)}/></label><label>Caption / scene description<input value={caption} maxLength={2000} onChange={e=>setCaption(e.target.value)}/></label><label>Creator / source credit<input value={credit} maxLength={2000} onChange={e=>setCredit(e.target.value)}/></label><label>Provenance<select value={origin} onChange={e=>setOrigin(e.target.value as ArtUpload['provenance'])}><option value="uploaded">Uploaded artwork</option><option value="external-generation">External generation result</option></select></label><div className="edition-actions"><button disabled={!file||!revision.trim()||!credit.trim()||!caption.trim()} onClick={()=>void(async()=>{if(request&&file&&await onUpload({requestId:request.id,file,note:revision,credit,caption,provenance:origin})){setFile(null);setRevision('');setCredit('');setCaption('');}})()}>Import as new version</button><button onClick={clear}>Clear unsaved fields</button></div></fieldset></section></div>
 <section className="edition-panel"><h2>Versions and approval</h2>{!art?.versions.length?<p>No artwork imported for this spread yet.</p>:art.versions.map((v,i)=>{const r=requests.find(r=>r.id===v.requestId);return <article className="production-version" key={v.id}><h3>Version {i+1}{art.approvedId===v.id?' · selected approval':''}</h3><p>{v.note} · {v.createdAt}</p><p>{v.image.width} × {v.image.height} pixels · {v.image.credit} · {v.image.provenance}</p>{r&&(v.image.width<r.width||v.image.height<r.height)&&<p>Below the request’s 300 dpi full-spread target. Smaller placements may still be suitable; Designer checks the placed size.</p>}<button disabled={busy||dirty||(art.approvedId===v.id&&artStatus(edition,planId)==='Approved artwork')} onClick={()=>void onAction({type:'approve-art',planId,versionId:v.id})}>{art.approvedId===v.id?'Reapprove against current direction':i===art.versions.length-1?'Approve this version':'Restore and approve this version'}</button></article>;})}<p>Approval is an explicit review against the current source, art guide, and references. Restoring a version preserves all later versions. Existing Designer placements keep their exact image until you replace it there.</p></section>
 <section className="edition-panel"><h2>Compare artwork across versions or spreads</h2><div className="production-comparison">{([{value:left,set:setLeft,version:a,label:'Left comparison'},{value:right,set:setRight,version:b,label:'Right comparison'}]).map(side=><div key={side.label}><label>{side.label}<select value={side.value||side.version?.id||''} onChange={e=>side.set(e.target.value)}>{all.map(v=><option key={v.id} value={v.id}>{plans.find(p=>p.id===v.planId)?.title} — {v.note}</option>)}</select></label>{side.version&&<><ReferencePicture image={side.version.image} onImage={onImage}/><p>{side.version.note}</p></>}</div>)}</div></section>
 </section>;
}
