"use client";
import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { artDirectionBrief, guideLayers, guideStatus, guideTextFields, latestGuide, outdatedGuideWork, proposeArtDirections, type ArtGuide } from '../../lib/art-direction';
import { inspirationAspects, inspirationBooks, type BookInspiration } from '../../lib/book-inspiration';
import type { Edition, EditionAction, Passage } from '../../lib/devotional-edition';

const labels: Record<typeof guideTextFields[number],string> = {name:'Direction name',purpose:'Audience and reading purpose',tone:'Tone',medium:'Illustration medium',texture:'Texture and backgrounds',linework:'Line treatment',detail:'Level of detail',spacing:'Spacing and reading areas',ornaments:'Ornaments, borders, and page furniture',environments:'Environments and architecture',culturalNotes:'Cultural details, clothing, and symbols',avoidances:'What to avoid'};
export function ArtDirectionWorkspace({edition,inspiration,busy,onAction,onDirty,onInspiration,onBrief}:{edition:Edition;inspiration?:BookInspiration;busy:boolean;onAction:(action:EditionAction)=>Promise<boolean>;onDirty:(value:boolean)=>void;onInspiration:()=>void;onBrief:()=>Promise<string>}) {
  const current=latestGuide(edition);
  const proposals=useMemo(()=>proposeArtDirections(edition,inspiration),[edition,inspiration]);
  const status=useMemo(()=>guideStatus(edition),[edition]);
  const productionBrief=useMemo(()=>status==='approved'?artDirectionBrief(edition,false):'',[edition,status]);
  const [draft,setDraft]=useState<ArtGuide | undefined>(current?.guide);
  const [base,setBase]=useState<ArtGuide | undefined>(current?.guide);
  const [reason,setReason]=useState('');
  const [localError,setLocalError]=useState('');
  const [feedback,setFeedback]=useState('');
  const [sampleId,setSampleId]=useState('');
  const passages=edition.passages.filter(p=>!p.retired);
  const sample=passages.find(p=>p.id===sampleId)||passages[0];
  const dirty=JSON.stringify(draft)!==JSON.stringify(base);
  const stale=status==='needs-review';
  useEffect(()=>{setDraft(current?.guide);setBase(current?.guide);setReason('');},[current?.version]);
  useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
  const useGuide=(guide:ArtGuide)=>{setDraft(structuredClone(guide));setReason('');setLocalError('');setFeedback('');requestAnimationFrame(()=>document.getElementById('art-guide-editor')?.scrollIntoView({block:'start'}));};
  async function save(){if(!draft)return; const ok=await onAction({type:'save-art-guide',guide:draft,reason});if(ok){setBase(draft);setReason('');}}
  async function copyBrief(){setLocalError('');try{const text=await onBrief();await navigator.clipboard.writeText(text);setFeedback('Approved production brief copied.');}catch(e){setLocalError(e instanceof Error?e.message:'Could not copy the brief.');}}
  async function downloadBrief(){setLocalError('');try{const text=await onBrief();const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`art-guide-v${current?.version}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setFeedback('Approved production brief downloaded.');}catch(e){setLocalError(e instanceof Error?e.message:'Could not download the brief.');}}
  if(!sample)return <section className="edition-panel"><h1>Art direction</h1><p>Add your manuscript in the source desk first. Visual proposals will use your own passages rather than placeholder text.</p></section>;
  return <div className="art-workspace">
    <section className="edition-panel art-heading"><div><h1>A visual direction for this edition</h1><p>{edition.metadata.type} · {edition.metadata.audience} · {edition.metadata.language} / {edition.metadata.script}</p><p>Compare composition studies using your manuscript, then refine and approve one guide. These studies show typography and spacing; finished illustration follows in production.</p></div><button disabled={busy||dirty} onClick={onInspiration}>Explore real-book references</button></section>
    {localError&&<p role="alert" className="edition-error">{localError}</p>}{feedback&&<p role="status">{feedback}</p>}
    {stale&&<p className="edition-error">The manuscript changed after version {current?.version}. Review the direction and save a new version before production.</p>}
    <label className="art-sample-select">Sample passage<select value={sample.id} onChange={e=>setSampleId(e.target.value)}>{passages.map((p,i)=><option key={p.id} value={p.id}>Passage {i+1} · {p.location||p.fields.original.text.slice(0,40)}</option>)}</select></label>
    <section aria-label="Proposed visual directions" className="art-proposals">{proposals.map((g,i)=><article key={g.layout} className="art-proposal"><div className="art-proposal-caption"><span>Direction {i+1}</span><h2>{g.name}</h2></div><GuideSample guide={g} passage={sample} title={edition.metadata.title} compact/><p>{g.spacing}</p><button disabled={busy} onClick={()=>useGuide(g)}>Refine direction {i+1}</button></article>)}</section>
    {draft&&<section id="art-guide-editor" className="art-edit-layout"><div className="edition-panel art-controls"><h2>Refine your guide</h2><p>Save creates a new draft version. Approval is a separate step.</p><fieldset disabled={busy}>
      {guideTextFields.map(key=><label key={key}>{labels[key]}{key==='name'?<input value={draft[key]} maxLength={3000} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<textarea value={draft[key]} maxLength={3000} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>)}
      <h3>Color roles</h3><div className="art-color-fields">{(['paper','ink','accent','support'] as const).map(role=><label key={role}>{role}<input type="color" value={draft.palette[role]} onChange={e=>setDraft({...draft,palette:{...draft.palette,[role]:e.target.value}})}/><span>{draft.palette[role]}</span></label>)}</div>
      <h3>Typography</h3>{guideLayers.map(layer=><div key={layer} className="art-type-row"><strong>{layer}</strong><label>Size (pt)<input aria-label={`${layer} size`} type="number" min={12} max={36} value={draft.typography[layer].size} onChange={e=>setDraft({...draft,typography:{...draft.typography,[layer]:{...draft.typography[layer],size:Number(e.target.value)}}})}/></label><label>Line height<input aria-label={`${layer} line height`} type="number" min={1.3} max={2.4} step={.1} value={draft.typography[layer].lineHeight} onChange={e=>setDraft({...draft,typography:{...draft.typography,[layer]:{...draft.typography[layer],lineHeight:Number(e.target.value)}}})}/></label><label>Family<select aria-label={`${layer} family`} value={draft.typography[layer].family} onChange={e=>setDraft({...draft,typography:{...draft.typography,[layer]:{...draft.typography[layer],family:e.target.value as 'serif'|'sans'}}})}><option value="serif">Serif</option><option value="sans">Sans serif</option></select></label></div>)}
      <label>Sample composition<select value={draft.layout} onChange={e=>setDraft({...draft,layout:e.target.value as ArtGuide['layout']})}><option value="quiet">Open reading page</option><option value="parallel">Separate reading zones</option><option value="framed">Framed reading area</option></select></label>
      <h3>Reference choices</h3><p>Record the references behind your direction. Edit the guide rules above to specify which qualities to carry forward.</p>{inspirationAspects.map(aspect=><label key={aspect}>{aspect}<select value={draft.references.references[aspect]||''} onChange={e=>setDraft({...draft,references:{...draft.references,references:{...draft.references.references,[aspect]:e.target.value||undefined}}})}><option value="">No reference</option>{inspirationBooks.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label>)}<label>Reference notes<textarea value={draft.references.notes} maxLength={2000} onChange={e=>setDraft({...draft,references:{...draft.references,notes:e.target.value}})}/></label>
      <label>Version note<input value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} placeholder="What changed, or why this direction fits"/></label><div className="edition-actions"><button className="edition-primary" disabled={!reason.trim()||(!dirty&&!stale)} onClick={()=>void save()}>Save guide version</button><button onClick={()=>{setDraft(base);setReason('');}}>Cancel unsaved changes</button></div>
    </fieldset></div><aside className="art-live-sample"><div className="edition-panel"><h2>Your sample</h2><p>Full passage · {sample.fields.original.status}</p><GuideSample guide={draft} passage={sample} title={edition.metadata.title}/><p className="art-sample-note">Illustration medium and cultural notes are production instructions. No finished artwork is generated in this sample.</p></div></aside></section>}
    <section id="art-approval" className="edition-panel"><h2>Approval and production</h2>{current?<><p>Version {current.version} · <strong>{status}</strong> · {current.guide.name}</p><p>{current.reason}</p><div className="edition-actions"><button disabled={busy||dirty||status!=='draft'} onClick={()=>void onAction({type:'approve-art-guide',version:current.version})}>Approve version {current.version}</button><button disabled={busy||dirty||status!=='approved'} onClick={()=>void copyBrief()}>Copy approved brief</button><button disabled={busy||dirty||status!=='approved'} onClick={()=>void downloadBrief()}>Download approved brief</button></div>{status==='approved'&&<details><summary>Read production instructions</summary><pre className="art-brief">{productionBrief}</pre></details>}</>:<p>Choose a proposal and save your guide to begin version history.</p>}
      {!!outdatedGuideWork(edition).length&&<><h3>Work needing review</h3>{outdatedGuideWork(edition).map(u=><p key={u.targetId}>{u.targetId} · made with version {u.version}</p>)}</>}
      <details><summary>Guide history ({edition.artDirection?.versions.length||0})</summary>{[...(edition.artDirection?.versions||[])].reverse().map(v=><article key={v.version}><h3>Version {v.version} · {v.guide.name}</h3><p>{v.createdAt} · {v.approvedAt?`Approved ${v.approvedAt}`:'Draft'} · {v.reason}</p><button disabled={busy} onClick={()=>useGuide(v.guide)}>Use version {v.version} as a new draft</button><details><summary>Saved guide details</summary><dl>{guideTextFields.map(k=><div key={k}><dt>{labels[k]}</dt><dd>{v.guide[k]}</dd></div>)}</dl></details></article>)}</details>
    </section>
  </div>;
}
function GuideSample({guide,passage,title,compact=false}:{guide:ArtGuide;passage:Passage;title:string;compact?:boolean}) {
  const style={'--guide-paper':guide.palette.paper,'--guide-ink':guide.palette.ink,'--guide-accent':guide.palette.accent,'--guide-support':guide.palette.support} as CSSProperties;
  return <div className={`guide-sample guide-${guide.layout}${compact?' guide-compact':''}`} style={style}><header>{title}</header><div className="guide-reading">{(['original','transliteration','translation','commentary'] as const).filter(f=>passage.fields[f].text).map(f=>{const type=guide.typography[f];const text=passage.fields[f].text;const shown=compact&&text.length>220?`${text.slice(0,220)}…`:text;return <div key={f} className={`guide-layer guide-layer-${f}`}>{f!=='original'&&<h3>{f}</h3>}<p style={{fontSize:compact?`${Math.max(12,type.size*.65)}px`:`${type.size}pt`,lineHeight:type.lineHeight,fontFamily:type.family==='serif'?"'Book Sanskrit', Georgia, serif":"system-ui, 'Book Sanskrit', sans-serif"}}>{shown}</p></div>;})}</div><footer style={{fontSize:compact?'12px':`${guide.typography.caption.size}pt`,lineHeight:guide.typography.caption.lineHeight,fontFamily:guide.typography.caption.family==='serif'?'Georgia,serif':'system-ui,sans-serif'}}>{compact?'Composition study · excerpts may be shortened':passage.location}</footer></div>;
}
