"use client";
import { useEffect, useState } from 'react';
import type { Edition, PassageField } from '../../lib/devotional-edition';
import { findingResolved, humanReviewCategories, openReviewFindings, releaseReviewIssues, renderReviewCurrent, reviewContext, reviewFindings, type BookReviewAction, type HumanReviewCategory, type ReviewFinding, type ReviewTarget } from '../../lib/book-review';
import { renderBookReview } from '../../lib/render-book-review';

type Props={edition:Edition;busy:boolean;onDirty:(dirty:boolean)=>void;onAction:(action:BookReviewAction)=>Promise<boolean>;onImage:(key:string)=>Promise<Blob>;onTarget:(target:ReviewTarget)=>void};
export function BookReviewWorkspace({edition:e,busy,onDirty,onAction,onImage,onTarget}:Props){
 const [running,setRunning]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
 const [filter,setFilter]=useState('Open'),[severity,setSeverity]=useState('All'),[category,setCategory]=useState('All');
 const [targetKey,setTargetKey]=useState('book'),[layerId,setLayerId]=useState(''),[field,setField]=useState<PassageField>('original'),[manualText,setManualText]=useState(''),[manualSeverity,setManualSeverity]=useState<'blocking'|'suggestion'>('suggestion');
 const [resolutionId,setResolutionId]=useState(''),[resolutionNote,setResolutionNote]=useState('');
 const [humanCategory,setHumanCategory]=useState<HumanReviewCategory>(humanReviewCategories[0]),[humanDecision,setHumanDecision]=useState<'approved'|'changes-required'>('changes-required'),[humanNote,setHumanNote]=useState('');
 const dirty=running||!!manualText||!!resolutionNote||!!humanNote;
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 const all=reviewFindings(e),open=openReviewFindings(e),release=releaseReviewIssues(e),current=renderReviewCurrent(e);
 const filtered=all.filter(f=>(filter==='All'||(filter==='Resolved')===findingResolved(e,f))&&(severity==='All'||f.severity===severity)&&(category==='All'||f.category===category));
 const resolve=all.find(f=>f.id===resolutionId);
 const selectedPlan=targetKey.startsWith('plan:')?targetKey.slice(5):'';
 const target=():ReviewTarget=>targetKey==='book'?{}:selectedPlan?{planId:selectedPlan,...(layerId?{layerId}:{})}:{passageId:targetKey.slice(8),field};
 const label=(t:ReviewTarget)=>[t.planId?e.storyboard?.find(p=>p.id===t.planId)?.title:'',t.passageId?e.passages.find(p=>p.id===t.passageId)?.location||t.passageId:'',t.field,t.layerId].filter(Boolean).join(' · ')||(t.workspace==='art'?'Art direction':'Whole book');
 async function audit(){setRunning(true);setError('');setProgress('Loading proof font…');const context=reviewContext(e);try{const results=await renderBookReview(e,onImage,(n,total)=>setProgress(`Checked ${n} of ${total} compositions`));if(await onAction({type:'save-render-review',context,results}))setProgress('Rendered audit saved.');}catch(err){setError(err instanceof Error?err.message:'Audit failed.');}finally{setRunning(false);}}
 function download(){const lines=[`# Book review — ${e.metadata.title}`,`Revision ${e.revision}`,`Rendered audit: ${current?'current':'missing or stale'}`,`Release blockers: ${release.length}`,'','This report does not certify artistic quality or printer output.','','## Open findings',...open.map(f=>`- [${f.severity}] ${label(f.target)}: ${f.message}`),'','## Human decisions',...(e.bookReview?.human||[]).map(h=>`- ${h.category}: ${h.decision} (${h.context===reviewContext(e)?'current':'stale'}) · ${h.at}\n  ${h.note}`),'','## Resolution history',...(e.bookReview?.decisions||[]).map(d=>`- ${d.issueId} (${d.context===reviewContext(e)?'current':'stale'}) · ${d.at}\n  ${d.note}`)];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='book-review.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 return <section className="book-review"><header className="edition-panel"><h1>Editorial, visual, and print review</h1><p>Resolve each issue where it occurs. Technical checks support review; they do not establish meaning, cultural accuracy, artistic quality, or a successful printed proof.</p><div className="book-review-counts"><strong>{open.filter(f=>f.severity==='blocking').length} blocking findings</strong><span>{open.filter(f=>f.severity==='suggestion').length} suggestions</span><span>{release.length} release requirements outstanding</span></div><div className="edition-actions"><button disabled={busy||running||!(e.compositions||[]).length} onClick={()=>void audit()}>{running?'Checking layouts…':'Run rendered audit'}</button><button disabled={busy||running} onClick={download}>Download review report</button></div><p role="status">{progress||`Rendered evidence: ${current?'current':'missing or stale'}`}</p>{error&&<p role="alert">{error}</p>}<p className="book-review-small">Checks the bundled font’s Unicode coverage, image retrieval/decoding, physical text overflow, and preview/proof markup parity. Complex-script shaping and the actual PDF still need visual inspection. Automatic blockers cannot be waived.</p></header>
 <section className="edition-panel"><h2>Findings</h2><div className="book-review-filters"><label>Finding state<select value={filter} onChange={ev=>setFilter(ev.target.value)}><option>Open</option><option>Resolved</option><option>All</option></select></label><label>Severity<select value={severity} onChange={ev=>setSeverity(ev.target.value)}><option>All</option><option>blocking</option><option>suggestion</option></select></label><label>Category<select value={category} onChange={ev=>setCategory(ev.target.value)}><option>All</option>{[...new Set(all.map(f=>f.category))].map(c=><option key={c}>{c}</option>)}</select></label></div>
 {!filtered.length&&<p>No findings match this view.</p>}{filtered.map(f=><article className={`book-finding book-finding-${f.severity}`} key={f.id}><div><strong>{findingResolved(e,f)?'Resolved':f.severity==='blocking'?'Blocking':'Suggestion'} · {f.category}</strong><small>{label(f.target)}</small><p>{f.message}</p></div><div className="edition-actions">{(f.target.workspace||f.target.planId||f.target.passageId)&&<button disabled={busy||dirty} onClick={()=>onTarget(f.target)}>Open {f.target.workspace==='art'?'art direction':f.target.workspace==='storyboard'?'storyboard plan':f.target.layerId?'affected layer':f.target.passageId?'affected passage':'affected spread'}</button>}{!f.id.startsWith('human:')&&(f.origin==='human'||f.severity==='suggestion')&&!findingResolved(e,f)&&<button disabled={busy||running||!!resolutionNote} onClick={()=>setResolutionId(f.id)}>Document resolution</button>}</div></article>)}
 {resolve&&<div className="book-resolution"><h3>Resolve: {resolve.message}</h3><label>Resolution note<textarea disabled={busy||running} value={resolutionNote} maxLength={4000} onChange={ev=>setResolutionNote(ev.target.value)}/></label><div className="edition-actions"><button disabled={busy||running||!resolutionNote.trim()} onClick={async()=>{if(await onAction({type:'resolve-review-issue',issueId:resolve.id,note:resolutionNote})){setResolutionId('');setResolutionNote('');}}}>Save resolution</button><button disabled={busy||running} onClick={()=>{setResolutionId('');setResolutionNote('');}}>Cancel resolution</button></div></div>}
 </section>
 <section className="edition-panel"><h2>Add a reviewer finding</h2><fieldset disabled={busy||running}><div className="book-review-filters"><label>Issue target<select value={targetKey} onChange={ev=>{setTargetKey(ev.target.value);setLayerId('');}}><option value="book">Whole book</option>{(e.storyboard||[]).map(p=><option key={p.id} value={`plan:${p.id}`}>{p.title}</option>)}{e.passages.filter(p=>!p.retired).map((p,i)=><option key={p.id} value={`passage:${p.id}`}>Passage {i+1}: {p.location}</option>)}</select></label>{selectedPlan&&<label>Layer<select value={layerId} onChange={ev=>setLayerId(ev.target.value)}><option value="">Whole spread</option>{e.compositions?.find(c=>c.planId===selectedPlan)?.layers.map(l=><option key={l.id} value={l.id}>{l.binding?.field||l.kind} · {l.id}</option>)}</select></label>}{targetKey.startsWith('passage:')&&<label>Text field<select value={field} onChange={ev=>setField(ev.target.value as PassageField)}>{['original','transliteration','translation','commentary','notes'].map(f=><option key={f}>{f}</option>)}</select></label>}<label>Issue severity<select value={manualSeverity} onChange={ev=>setManualSeverity(ev.target.value as typeof manualSeverity)}><option>suggestion</option><option>blocking</option></select></label></div><label>Finding description<textarea maxLength={4000} value={manualText} onChange={ev=>setManualText(ev.target.value)}/></label><div className="edition-actions"><button disabled={!manualText.trim()} onClick={async()=>{if(await onAction({type:'add-review-issue',severity:manualSeverity,message:manualText,target:target()}))setManualText('');}}>Save finding</button><button onClick={()=>setManualText('')}>Clear finding</button></div></fieldset></section>
 <section className="edition-panel"><h2>Human review decisions</h2><p>Record an actual review with evidence in the note. Choosing approval is your editorial decision, not an automatic result. Book edits make these decisions stale.</p><ul>{humanReviewCategories.map(c=>{const last=e.bookReview?.human.filter(h=>h.category===c).at(-1);return <li key={c}>{c}: {last?(last.context===reviewContext(e)?last.decision:'stale'):'not reviewed'}</li>;})}</ul><fieldset disabled={busy||running}><div className="book-review-filters"><label>Review category<select value={humanCategory} onChange={ev=>setHumanCategory(ev.target.value as HumanReviewCategory)}>{humanReviewCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Decision<select value={humanDecision} onChange={ev=>setHumanDecision(ev.target.value as typeof humanDecision)}><option value="changes-required">Changes required</option><option value="approved">Approved after review</option></select></label></div><label>Review evidence / note<textarea value={humanNote} maxLength={4000} onChange={ev=>setHumanNote(ev.target.value)}/></label><div className="edition-actions"><button disabled={!humanNote.trim()} onClick={async()=>{if(await onAction({type:'record-human-review',category:humanCategory,decision:humanDecision,note:humanNote}))setHumanNote('');}}>Save human decision</button><button onClick={()=>setHumanNote('')}>Clear review note</button></div></fieldset><details><summary>Decision and resolution history</summary>{e.bookReview?.human.slice().reverse().map((h,i)=><p key={`h${i}`}>{h.category} · {h.decision} · {h.at} · {h.note}</p>)}{e.bookReview?.decisions.slice().reverse().map((d,i)=><p key={`d${i}`}>{d.issueId} · {d.at} · {d.note}</p>)}</details></section>
 </section>;
}
