"use client";
import { useEffect, useRef, useState } from 'react';
import type { Edition } from '../../lib/devotional-edition';
import { bookPartRoles, productionContext, productionReadiness, productionState, productionStates, type BookPartRole, type BookProductionAction, type PrinterCover } from '../../lib/book-production';
import { compositionFormat, compositionMarkup, layerText } from '../../lib/spread-composition';
import { storyboardIssues, storyboardPages } from '../../lib/storyboard';

type Props={edition:Edition;busy:boolean;onAction:(a:BookProductionAction)=>Promise<boolean>;onImage:(key:string)=>Promise<Blob>;onDirty:(dirty:boolean)=>void;onDesign:(id:string)=>void};
export function BookProductionWorkspace({edition:e,busy,onAction,onImage,onDirty,onDesign}:Props){
 const plans=e.storyboard||[],data=e.bookProduction,pages=storyboardPages(plans);
 const [filter,setFilter]=useState('All'),[batchFilter,setBatchFilter]=useState(''),[limit,setLimit]=useState(12),[selected,setSelected]=useState<string[]>([]),[batchName,setBatchName]=useState('');
 const [reviewId,setReviewId]=useState(''),[note,setNote]=useState(''),[checks,setChecks]=useState({meaning:false,artwork:false,textFit:false});
 const [role,setRole]=useState<BookPartRole>('Title page'),[title,setTitle]=useState(''),[body,setBody]=useState('');
 const [cover,setCover]=useState<PrinterCover>(data?.cover||{printer:'',templateReference:'',flatWidth:0,flatHeight:0,spineWidth:0,bleed:0,notes:''});
 useEffect(()=>{setCover(data?.cover||{printer:'',templateReference:'',flatWidth:0,flatHeight:0,spineWidth:0,bleed:0,notes:''});},[data?.cover]);
 const coverDirty=JSON.stringify(cover)!==JSON.stringify(data?.cover||{printer:'',templateReference:'',flatWidth:0,flatHeight:0,spineWidth:0,bleed:0,notes:''});
 const dirty=!!(batchName||note||title||body||coverDirty);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 const context=productionContext(e,reviewId);
 useEffect(()=>{setChecks({meaning:false,artwork:false,textFit:false});},[context,reviewId]);
 const batch=data?.batches.find(b=>b.id===batchFilter);
 const shown=plans.filter(p=>(filter==='All'||productionState(e,p.id)===filter)&&(!batch||batch.planIds.includes(p.id)));
 const review=plans.find(p=>p.id===reviewId),issues=review?productionReadiness(e,reviewId):[];
 const coverage=storyboardIssues(e).filter(i=>i.blocking);
 async function reviewAction(kind:'submit'|'approve'|'rework'){if(await onAction({type:'review-production-spread',planId:reviewId,kind,note,checks})){setNote('');setChecks({meaning:false,artwork:false,textFit:false});}}
 return <section className="book-production">
  <header className="edition-panel"><h1>Full-book production</h1><p>Organize the work in batches. Review the whole book together, then return to individual spreads for changes. Batches track imported/manual work; they do not run image generation.</p><div className="book-progress">{productionStates.map(status=><div key={status}><strong>{plans.filter(p=>productionState(e,p.id)===status).length}</strong><span>{status}</span></div>)}</div><p>{coverage.length} content-allocation issues remain. Production approval records a review of one version; final editorial and print release checks are separate.</p></header>
  <section className="edition-panel"><h2>Production batches</h2><p>Select up to 50 plans in the contact sheet, then name the batch. Each spread belongs to at most one active batch.</p><label>Batch name<input disabled={busy} maxLength={200} value={batchName} onChange={ev=>setBatchName(ev.target.value)}/></label><div className="edition-actions"><button disabled={busy||!batchName.trim()||!selected.length} onClick={async()=>{if(await onAction({type:'save-production-batch',name:batchName,planIds:selected})){setBatchName('');setSelected([]);}}}>Create batch ({selected.length})</button><button disabled={busy} onClick={()=>{setBatchName('');setSelected([]);}}>Clear batch selection</button></div>
   {data?.batches.map(b=><article key={b.id} className="book-batch"><div><strong>{b.name}{b.archived?' · archived':''}</strong><p>{b.planIds.filter(id=>plans.some(p=>p.id===id)&&productionState(e,id)==='Approved').length} approved / {b.planIds.filter(id=>plans.some(p=>p.id===id)).length} active plans{b.planIds.some(id=>!plans.some(p=>p.id===id))?' · contains removed plans':''}</p></div><button disabled={busy} onClick={()=>void onAction({type:'archive-production-batch',id:b.id,archived:!b.archived})}>{b.archived?'Restore batch':'Archive batch'}</button></article>)}
  </section>
  <section className="edition-panel"><h2>Whole-book contact sheet</h2><p>Compare composition, palette, character details, and text density. Use Designer at actual size to judge readability.</p><div className="book-controls"><label>Review status<select value={filter} onChange={ev=>{setFilter(ev.target.value);setLimit(12);}}><option>All</option>{productionStates.map(s=><option key={s}>{s}</option>)}</select></label><label>Batch filter<select value={batchFilter} onChange={ev=>{setBatchFilter(ev.target.value);setLimit(12);}}><option value="">All plans</option>{data?.batches.map(b=><option key={b.id} value={b.id}>{b.name}{b.archived?' (archived)':''}</option>)}</select></label></div>
   <div className="book-contact-sheet">{shown.slice(0,limit).map(p=>{const page=pages.find(a=>a.id===p.id)!;return <article key={p.id}><ContactPreview edition={e} planId={p.id} onImage={onImage}/><label className="book-select"><input type="checkbox" disabled={busy||(!selected.includes(p.id)&&selected.length>=50)} checked={selected.includes(p.id)} onChange={ev=>setSelected(ev.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/><strong>{p.title}</strong></label><p>{productionState(e,p.id)} · {p.kind==='cover'?'Cover concept':`Pages ${page.pages.join('–')}`}{page.blankBefore?` · blank p${page.blankBefore} before`:''}</p><small>{p.family} · {e.compositions?.find(c=>c.planId===p.id)?.layers.filter(l=>l.kind==='text').reduce((n,l)=>n+layerText(e,l).length,0)||0} text characters</small><div className="edition-actions"><button disabled={busy||dirty} onClick={()=>onDesign(p.id)}>Design {p.title}</button><button disabled={busy||!!note} onClick={()=>{setReviewId(p.id);setChecks({meaning:false,artwork:false,textFit:false});}}>Review {p.title}</button></div></article>;})}</div>
   {!shown.length&&<p>No plans match this view. Create plans in Storyboard or add a book section below.</p>}{shown.length>limit&&<button onClick={()=>setLimit(limit+12)}>Show next 12 plans ({shown.length-limit} remaining)</button>}
  </section>
  {review&&<section className="edition-panel"><h2>Review: {review.title}</h2><p>{productionState(e,reviewId)}</p>{issues.length>0&&<ul>{issues.map(i=><li key={i}>{i}</li>)}</ul>}<fieldset disabled={busy}><label>Review or rework note<textarea value={note} maxLength={2000} onChange={ev=>setNote(ev.target.value)}/></label>{([['meaning','I reviewed the meaning and source accuracy.'],['artwork','I reviewed the artwork, cultural appropriateness, and continuity.'],['textFit','I checked text fit and readability at actual size in Designer.']] as const).map(([key,label])=><label className="book-select" key={key}><input type="checkbox" checked={checks[key]} onChange={ev=>setChecks({...checks,[key]:ev.target.checked})}/>{label}</label>)}<div className="edition-actions"><button disabled={!note.trim()} onClick={()=>void reviewAction('submit')}>Send for review</button><button disabled={!note.trim()||!!issues.length||!Object.values(checks).every(Boolean)} onClick={()=>void reviewAction('approve')}>Approve production review</button><button disabled={!note.trim()} onClick={()=>void reviewAction('rework')}>Request rework on this spread</button><button onClick={()=>{setNote('');setReviewId('');}}>Close review</button></div></fieldset><details><summary>Review history</summary>{data?.reviews.filter(r=>r.planId===reviewId).slice().reverse().map((r,i)=><p key={i}>{r.kind} · {r.at} · {r.note}</p>)}</details></section>}
  <section className="edition-panel"><h2>Front matter, back matter, and cover concepts</h2><p>Add only the sections this book needs. Supply the actual editorial text; original scripture belongs in Source desk. The saved page is editable in Designer and starts as a draft.</p><fieldset disabled={busy}><div className="book-controls"><label>Section type<select value={role} onChange={ev=>setRole(ev.target.value as BookPartRole)}>{bookPartRoles.map(r=><option key={r}>{r}</option>)}</select></label><label>Section title<input maxLength={200} value={title} onChange={ev=>setTitle(ev.target.value)}/></label></div><label>Section text<textarea maxLength={10000} value={body} onChange={ev=>setBody(ev.target.value)}/></label><div className="edition-actions"><button disabled={!title.trim()||!body.trim()} onClick={async()=>{if(await onAction({type:'add-book-part',role,title,body})){setTitle('');setBody('');}}}>Add section</button><button onClick={()=>{setTitle('');setBody('');}}>Clear section text</button></div></fieldset><p>Cover concepts use the edition’s trim size and latest art-guide colors. They are separate front/back designs, not a printer-ready wrap.</p></section>
  <details className="edition-panel"><summary>Printer-supplied cover requirements</summary><p>Transcribe the selected printer’s actual template. Flat dimensions include bleed. This record does not calculate a spine from page count or create a wrap-around export.</p><fieldset disabled={busy}><label>Printer<input maxLength={200} value={cover.printer} onChange={ev=>setCover({...cover,printer:ev.target.value})}/></label><label>Template URL or document reference<input maxLength={2000} value={cover.templateReference} onChange={ev=>setCover({...cover,templateReference:ev.target.value})}/></label><div className="book-controls">{([['flatWidth','Flat width'],['flatHeight','Flat height'],['spineWidth','Spine width'],['bleed','Bleed']] as const).map(([key,label])=><label key={key}>{label} (mm)<input type="number" min={0} step={.1} value={cover[key]} onChange={ev=>setCover({...cover,[key]:Number(ev.target.value)})}/></label>)}</div><label>Binding / flap / printer notes<textarea maxLength={4000} value={cover.notes} onChange={ev=>setCover({...cover,notes:ev.target.value})}/></label><div className="edition-actions"><button disabled={!coverDirty||!cover.printer.trim()||!cover.templateReference.trim()} onClick={()=>void onAction({type:'save-printer-cover',cover})}>Save printer requirements</button><button onClick={()=>setCover(data?.cover||{printer:'',templateReference:'',flatWidth:0,flatHeight:0,spineWidth:0,bleed:0,notes:''})}>Discard printer edits</button></div></fieldset></details>
 </section>;
}
function ContactPreview({edition:e,planId,onImage}:{edition:Edition;planId:string;onImage:(key:string)=>Promise<Blob>}){
 const holder=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false),[assets,setAssets]=useState<Record<string,string>>({}),[error,setError]=useState(''),[scale,setScale]=useState(.2);
 const c=e.compositions?.find(c=>c.planId===planId),p=e.storyboard?.find(p=>p.id===planId),f=compositionFormat(e,c),w=f.width*(p?.kind==='spread'?2:1)+2*f.bleed;
 const keys=JSON.stringify([...new Set(c?.layers.filter(l=>l.kind==='image'&&!l.hidden).map(l=>l.imageKey)||[])]);
 useEffect(()=>{const el=holder.current;if(!el)return;const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){setVisible(true);observer.disconnect();}},{rootMargin:'300px'});observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{const el=holder.current;if(!el)return;const observer=new ResizeObserver(()=>setScale(el.clientWidth/(w*96/25.4)));observer.observe(el);return()=>observer.disconnect();},[w]);
 useEffect(()=>{if(!visible)return;let active=true;const urls:string[]=[];setAssets({});setError('');void(async()=>{try{const entries=await Promise.all((JSON.parse(keys) as string[]).map(async key=>{const blob=await onImage(key);if(!active)return [key,''];const url=URL.createObjectURL(blob);urls.push(url);return [key,url];}));if(active)setAssets(Object.fromEntries(entries));}catch{if(active)setError('Artwork unavailable. Open Designer to retry.');}})();return()=>{active=false;urls.forEach(url=>URL.revokeObjectURL(url));};},[keys,visible,onImage]);
 return <><div className="book-contact-preview" ref={holder} style={{height:c?(f.height+2*f.bleed)*96/25.4*scale:160}}>{c?<div aria-label={`Composition preview: ${p?.title}`} role="img" style={{transform:`scale(${scale})`,transformOrigin:'top left'}} dangerouslySetInnerHTML={{__html:visible?compositionMarkup(e,c,assets):''}}/>:<p>No composition yet</p>}</div>{error&&<p role="alert">{error}</p>}</>;
}
