"use client";
import { useEffect, useState } from 'react';
import type { Edition, PassageField } from '../../lib/devotional-edition';
import { blankSpread, compositionFamilies, pageKinds, spreadStatus, storyboardIssues, storyboardPages, type SpreadPlan, type StoryboardAction } from '../../lib/storyboard';

export function StoryboardWorkspace({edition,busy,onAction,onDirty}:{edition:Edition;busy:boolean;onAction:(action:StoryboardAction)=>Promise<boolean>;onDirty:(dirty:boolean)=>void}) {
  const plans=edition.storyboard||[], pages=storyboardPages(plans), issues=storyboardIssues(edition);
  const [selected,setSelected]=useState(''), [draft,setDraft]=useState<SpreadPlan>(blankSpread), [dragged,setDragged]=useState('');
  const saved=plans.find(p=>p.id===selected);
  const dirty=JSON.stringify(draft)!==JSON.stringify(saved||blankSpread());
  useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
  const select=(plan?:SpreadPlan)=>{setSelected(plan?.id||'');setDraft(structuredClone(plan||blankSpread()));};
  const update=<K extends keyof SpreadPlan>(key:K,value:SpreadPlan[K])=>setDraft({...draft,[key]:value});
  const reorder=async (from:string,to:string)=>{const ids=plans.map(p=>p.id);ids.splice(ids.indexOf(from),1);ids.splice(plans.findIndex(p=>p.id===to),0,from);await onAction({type:'reorder-spreads',ids});};
  const active=edition.passages.filter(p=>!p.retired);
  return <section className="storyboard-workspace">
    <header className="edition-panel"><h1>Whole-book storyboard</h1><p>Plan the reading rhythm before making finished pages. Thumbnails represent facing-page structure, not final artwork.</p><p>{plans.length} plans · {issues.filter(i=>i.blocking).length} content issues · {issues.filter(i=>!i.blocking).length} review suggestions</p></header>
    <div className="storyboard-overview" aria-label="Storyboard overview">{plans.map((plan,index)=><article key={plan.id} draggable={!busy&&!dirty} onDragStart={()=>setDragged(plan.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged&&!busy&&!dirty)void reorder(dragged,plan.id);setDragged('');}}>
      <button disabled={busy||dirty} onClick={()=>select(plan)} aria-current={selected===plan.id?'true':undefined}><div className={`storyboard-thumb ${plan.kind}`}><span>{plan.family}</span>{plan.kind==='spread'&&<span>{plan.allocations.length} allocations</span>}</div><strong>{plan.title}</strong><small>{plan.kind==='cover'?'Cover (unnumbered)':`Pages ${pages[index].pages.join('–')}`}{pages[index].blankBefore?` · blank p${pages[index].blankBefore} before`:''}</small><small>{spreadStatus(edition,plan)} · Artwork not started</small></button>
      <div className="edition-actions"><button aria-label={`Move ${plan.title} earlier`} disabled={busy||dirty||index===0} onClick={()=>void reorder(plan.id,plans[index-1].id)}>← Earlier</button><button aria-label={`Move ${plan.title} later`} disabled={busy||dirty||index===plans.length-1} onClick={()=>void reorder(plan.id,plans[index+1].id)}>Later →</button></div>
    </article>)}</div>
    <div className="storyboard-columns"><section className="edition-panel"><div className="edition-actions"><h2>{saved?'Edit plan':'New page or spread'}</h2><button disabled={busy||dirty} onClick={()=>select()}>New plan</button></div><fieldset disabled={busy}>
      <label>Plan title<input value={draft.title} maxLength={4000} onChange={e=>update('title',e.target.value)}/></label>
      <div className="storyboard-fields"><label>Page kind<select value={draft.kind} onChange={e=>update('kind',e.target.value as SpreadPlan['kind'])}>{pageKinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Composition family<select value={draft.family} onChange={e=>update('family',e.target.value as SpreadPlan['family'])}>{compositionFamilies.map(k=><option key={k}>{k}</option>)}</select></label></div>
      <p>A single interior page follows the current left/right sequence. Facing pairs always begin on an even page; any necessary blank is shown in the overview.</p>
      {([['purpose','Reading purpose'],['tone','Emotional tone'],['concept','Scene or visual concept'],['composition','Composition and illustration requirements'],['textArea','Reserved text areas'],['before','Connection to preceding pages'],['after','Connection to following pages']] as const).map(([key,label])=><label key={key}>{label}<textarea value={draft[key]} maxLength={4000} onChange={e=>update(key,e.target.value)}/></label>)}
      <label>Approximate text budget (characters)<input type="number" min={1} max={50000} value={draft.textBudget} onChange={e=>update('textBudget',Number(e.target.value))}/></label>
      <h3>Passage allocation</h3><p>Ranges use zero-based character boundaries in the original text. Continue a long passage on another spread with an adjoining range. Selected supplementary fields also support continuation ranges.</p>
      {active.map((p,index)=><div className="storyboard-allocation" key={p.id}><button onClick={()=>update('allocations',[...draft.allocations,{passageId:p.id,fields:['original'],start:0,end:p.fields.original.text.length}])}>Add passage {index+1}</button><span>{p.location || p.fields.original.text.slice(0,70)}</span></div>)}
      {draft.allocations.map((a,index)=>{const p=edition.passages.find(p=>p.id===a.passageId);const change=(patch:Partial<typeof a>)=>update('allocations',draft.allocations.map((old,i)=>i===index?{...old,...patch}:old));return <article className="storyboard-allocation-editor" key={index}><strong>{p?.location||a.passageId}{p?.retired?' (retired — reassign)':''}</strong><div className="storyboard-fields"><label>Start boundary<input type="number" min={0} value={a.start} onChange={e=>change({start:Number(e.target.value)})}/></label><label>End boundary<input type="number" min={1} value={a.end} onChange={e=>change({end:Number(e.target.value)})}/></label></div><div className="edition-actions">{(['original','transliteration','translation','commentary'] as PassageField[]).map(f=><label key={f}><input type="checkbox" checked={a.fields.includes(f)} onChange={e=>change({fields:e.target.checked?[...a.fields,f]:a.fields.filter(old=>old!==f)})}/>{f}</label>)}</div><p className="storyboard-text">{p?.fields.original.text.slice(a.start,a.end)}</p>{a.fields.filter(f=>f!=='original').map(f=>{const range=a.ranges?.[f]||{start:0,end:p?.fields[f].text.length||0};return <div key={f}><strong>{f} continuation</strong><div className="storyboard-fields"><label>{f} start<input type="number" min={0} value={range.start} onChange={e=>change({ranges:{...a.ranges,[f]:{...range,start:Number(e.target.value)}}})}/></label><label>{f} end<input type="number" min={1} value={range.end} onChange={e=>change({ranges:{...a.ranges,[f]:{...range,end:Number(e.target.value)}}})}/></label></div><p className="storyboard-text">{p?.fields[f].text.slice(range.start,range.end)}</p></div>;})}<button onClick={()=>update('allocations',draft.allocations.filter((_,i)=>i!==index))}>Remove allocation {index+1}</button></article>;})}
      <div className="edition-actions"><button className="edition-primary" disabled={!dirty||!draft.title.trim()} onClick={()=>void(async()=>{if(await onAction({type:'save-spread',plan:draft}))select();})()}>Save plan</button><button onClick={()=>select(saved)}>Cancel changes</button>{saved&&<><button disabled={dirty||spreadStatus(edition,saved)==='Approved plan'} onClick={()=>void(async()=>{if(await onAction({type:'approve-spread',id:saved.id}))select();})()}>Approve plan</button><button disabled={dirty} onClick={()=>void(async()=>{if(await onAction({type:'delete-spread',id:saved.id}))select();})()}>Delete plan</button></>}</div>
    </fieldset></section><aside className="edition-panel"><h2>Content and rhythm review</h2><p>All active original passages must be allocated. Supplementary fields are optional. Warnings do not force visual variety or smaller text.</p>{!issues.length?<p>No allocation issues found.</p>:issues.map((issue,index)=><article key={index}><strong>{issue.blocking?'Content issue':'Review suggestion'}</strong><p>{plans.find(p=>p.id===issue.target)?.title || edition.passages.find(p=>p.id===issue.target)?.location || issue.target}</p><p>{issue.message}</p>{plans.some(p=>p.id===issue.target)&&<button disabled={busy||dirty} onClick={()=>select(plans.find(p=>p.id===issue.target))}>Open affected plan</button>}</article>)}</aside></div>
  </section>;
}
