"use client";
import { useEffect, useRef, useState } from 'react';
import { approvedReference, emptyReferenceSpec, referenceKinds, referenceSpecFields, referenceViews, type ReferenceAction, type ReferenceImage, type ReferenceSpec, type VisualReference } from '../../lib/visual-references';
import { guideStatus, latestGuide } from '../../lib/art-direction';
import type { Edition } from '../../lib/devotional-edition';
export type ReferenceUpload = {referenceId:string;file:File;view:ReferenceImage['view'];caption:string;credit:string;provenance:ReferenceImage['provenance']};
const labels:Record<typeof referenceSpecFields[number],string>={name:'Name',role:'Narrative role or purpose',features:'Identifying features',proportions:'Proportions and scale',clothing:'Clothing or surface materials',ornaments:'Ornaments and distinctive details',colors:'Colors and palette',objects:'Held objects or related objects',poses:'Poses, views, or spatial arrangement',expressions:'Expressions or atmosphere',culturalNotes:'Reviewed cultural and source notes'};
export function VisualReferenceWorkspace({edition,busy,onAction,onUpload,onImage,onPackage,onDirty}:{edition:Edition;busy:boolean;onAction:(action:ReferenceAction)=>Promise<boolean>;onUpload:(input:ReferenceUpload)=>Promise<boolean>;onImage:(key:string)=>Promise<Blob>;onPackage:(id:string)=>Promise<void>;onDirty:(value:boolean)=>void}){
 const refs=edition.visualReferences||[];
 const [selected,setSelected]=useState(refs.find(r=>!r.archived)?.id||'new');
 const ref=refs.find(r=>r.id===selected);
 const latest=ref?.versions.at(-1),approved=ref&&approvedReference(ref);
 const [draft,setDraft]=useState<ReferenceSpec>(latest?.spec||emptyReferenceSpec());
 const [images,setImages]=useState<string[]>(latest?.images.map(i=>i.id)||[]);
 const [reason,setReason]=useState('');
 const [file,setFile]=useState<File|null>(null);
 const [view,setView]=useState<ReferenceImage['view']>('front');
 const [caption,setCaption]=useState('');
 const [credit,setCredit]=useState('');
 const [provenance,setProvenance]=useState<ReferenceImage['provenance']>('uploaded');
 const [left,setLeft]=useState(0),[right,setRight]=useState(0);
 const [note,setNote]=useState('');
 const existingChanged=JSON.stringify(draft)!==JSON.stringify(latest?.spec||emptyReferenceSpec())||JSON.stringify(images)!==JSON.stringify(latest?.images.map(i=>i.id)||[]);
 const dirty=existingChanged||!!file;
 const guide=latestGuide(edition);
 const known=[...new Map((ref?.versions.flatMap(v=>v.images)||[]).map(i=>[i.id,i])).values()];
 useEffect(()=>{setDraft(latest?.spec||emptyReferenceSpec());setImages(latest?.images.map(i=>i.id)||[]);setReason('');setFile(null);setCaption('');setLeft(approved?.version||latest?.version||0);setRight(latest?.version||0);},[selected,latest?.version]);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 async function save(){const ok=await onAction({type:'save-reference',id:ref?.id,spec:draft,imageIds:images,reason});if(ok&&!ref){setDraft(emptyReferenceSpec());setImages([]);setReason('');setNote('Reference created. Select it from the library to upload images.');}}
 async function upload(){if(!ref||!file)return;const ok=await onUpload({referenceId:ref.id,file,view,caption,credit,provenance});if(ok){setFile(null);setCaption('');}}
 return <div className="reference-workspace"><section className="edition-panel"><h1>Characters and visual references</h1><p>Keep recurring figures, environments, and objects consistent. A new draft leaves the approved identity intact until you approve its replacement.</p><p>Current art guide: {guide?`version ${guide.version} · ${guideStatus(edition)}`:'not yet saved'}</p>{note&&<p role="status">{note}</p>}</section>
 <div className="reference-layout"><aside className="edition-panel reference-library"><button disabled={busy||dirty} onClick={()=>setSelected('new')}>New reference</button>{refs.map(r=><button key={r.id} disabled={busy||dirty} aria-current={r.id===selected?'true':undefined} onClick={()=>setSelected(r.id)}><strong>{r.versions.at(-1)?.spec.name}</strong><span>{r.versions.at(-1)?.spec.kind} · {r.archived?'archived':r.approvedVersion?`approved v${r.approvedVersion}`:'draft'}</span></button>)}</aside>
 <section className="edition-panel"><h2>{ref?'Reference details':'Create a reference'}</h2>{ref&&<p>Draft version {latest?.version} · {approved?`Production identity: version ${approved.version}`:'No approved identity yet'}</p>}
 <fieldset disabled={busy||ref?.archived}><label>Reference type<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as ReferenceSpec['kind']})}>{referenceKinds.map(k=><option key={k}>{k}</option>)}</select></label><div className="reference-fields">{referenceSpecFields.map(key=><label key={key}>{labels[key]}{['name','role','features','colors','culturalNotes'].includes(key)?' *':''}{key==='name'?<input value={draft[key]} maxLength={3000} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<textarea value={draft[key]} maxLength={3000} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</label>)}</div>
 {!!known.length&&<><h3>Images in this draft</h3><p>Unchecking an image removes it only from the next draft. Earlier versions retain it.</p><div className="reference-image-grid">{known.map(image=><label className="reference-image-choice" key={image.id}><ReferencePicture image={image} onImage={onImage}/><span><input type="checkbox" checked={images.includes(image.id)} onChange={e=>setImages(e.target.checked?[...images,image.id]:images.filter(id=>id!==image.id))}/>{image.view} · {image.caption}</span></label>)}</div></>}
 <label>Revision note<input value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} placeholder="Describe this identity or the revision"/></label><div className="edition-actions"><button className="edition-primary" disabled={!reason.trim()||!!file} onClick={()=>void save()}>Save reference draft</button><button onClick={()=>{setDraft(latest?.spec||emptyReferenceSpec());setImages(latest?.images.map(i=>i.id)||[]);setReason('');setFile(null);}}>Cancel unsaved changes</button></div></fieldset>
 {ref&&<><div className="edition-actions"><button disabled={busy||dirty||!!ref.archived||!latest?.images.length||guideStatus(edition)!=='approved'||latest?.artGuideVersion!==guide?.version||ref.approvedVersion===latest?.version} onClick={()=>void onAction({type:'approve-reference',id:ref.id,version:latest!.version})}>Approve version {latest?.version}</button><button disabled={busy||dirty} onClick={()=>void onAction({type:'archive-reference',id:ref.id,archived:!ref.archived})}>{ref.archived?'Restore reference':'Archive reference'}</button></div>{latest?.artGuideVersion!==guide?.version&&<p className="edition-error">The art guide changed. Review the reference details and images, then save a new draft before approval.</p>}
 <details open={!latest?.images.length}><summary>Import a reference view</summary><p>PNG, JPEG, or WebP up to 10 MB. Upload separate views or a reference sheet. Every import creates a new draft version.</p><fieldset disabled={busy||ref.archived||existingChanged}><label>Image<input key={`${ref.id}-${latest?.version}`} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);e.currentTarget.value='';}}/></label>{file&&<p>Selected file: {file.name}</p>}<label>View<select value={view} onChange={e=>setView(e.target.value as ReferenceImage['view'])}>{referenceViews.map(v=><option key={v}>{v}</option>)}</select></label><label>Caption / identifying details<input value={caption} maxLength={2000} onChange={e=>setCaption(e.target.value)}/></label><label>Creator / source credit<input value={credit} maxLength={2000} onChange={e=>setCredit(e.target.value)}/></label><label>Image origin<select value={provenance} onChange={e=>setProvenance(e.target.value as ReferenceImage['provenance'])}><option value="uploaded">Uploaded artwork</option><option value="external-generation">External generation result</option></select></label><button disabled={!file||!caption.trim()||!credit.trim()} onClick={()=>void upload()}>Upload view as a draft</button></fieldset></details>
 <details><summary>Reference-guided generation</summary><p>Download the current specification, approved art guide, and identity images as a ZIP. Use it with your image tool, then import the results above as external-generation drafts. No image service is called here.</p><button disabled={busy||dirty||ref.archived||guideStatus(edition)!=='approved'} onClick={()=>void onPackage(ref.id)}>Download reference request ZIP</button></details></>}
 </section></div>
 {ref&&<section className="edition-panel"><h2>Continuity comparison</h2><p>Compare versions side by side before approval. Check identifying features, proportions, clothing, ornaments, colors, poses, and cultural details.</p><div className="reference-compare">{[{value:left,set:setLeft,label:'Left version'},{value:right,set:setRight,label:'Right version'}].map(side=><div key={side.label}><label>{side.label}<select value={side.value} onChange={e=>side.set(Number(e.target.value))}>{ref.versions.map(v=><option key={v.version} value={v.version}>Version {v.version} · {v.approvedAt?'approved at review':'draft'}</option>)}</select></label><VersionPanel reference={ref} version={side.value} onImage={onImage}/></div>)}</div></section>}
 </div>;
}
export function ReferencePicture({image,onImage}:{image:ReferenceImage;onImage:(key:string)=>Promise<Blob>}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 const container=useRef<HTMLElement>(null);
 useEffect(()=>{let alive=true;let objectUrl='';let started=false;setError('');setUrl('');const load=()=>{if(started)return;started=true;onImage(image.key).then(blob=>{objectUrl=URL.createObjectURL(blob);if(alive)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}).catch(()=>{if(alive)setError('Image unavailable. Retain this record and upload a replacement draft.');});};const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){load();observer.disconnect();}},{rootMargin:'300px'});if(container.current)observer.observe(container.current);return()=>{alive=false;observer.disconnect();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[image.key,onImage]);
 return <figure ref={container} className="reference-picture">{error?<p role="status">{error}</p>:url?<img src={url} alt={`${image.view}: ${image.caption}`} onError={()=>setError('This file could not be decoded. Upload a valid raster image.')}/>:<p>Loading reference…</p>}<figcaption>{image.caption}<br/>{image.width} × {image.height} · {image.credit}</figcaption></figure>;
}
function VersionPanel({reference,version,onImage}:{reference:VisualReference;version:number;onImage:(key:string)=>Promise<Blob>}){
 const v=reference.versions.find(v=>v.version===version);if(!v)return null;
 return <article className="reference-version"><h3>{v.spec.name} · v{v.version}</h3><p>{v.reason}</p><p>Art guide {v.artGuideVersion} · {v.createdAt}</p>{v.images.length?v.images.map(i=><ReferencePicture key={i.id} image={i} onImage={onImage}/>):<p>No images in this version.</p>}<dl>{referenceSpecFields.filter(k=>k!=='name'&&v.spec[k]).map(k=><div key={k}><dt>{labels[k]}</dt><dd>{v.spec[k]}</dd></div>)}</dl></article>;
}
