'use client';
import type {TemplateBook} from '../../lib/template-book';
import {defaultBookCompletion,type BookCompletion} from '../../lib/book-completion';
export default function CompletionEditor({book,images,onChange,onReplace}:{book:TemplateBook;images:Record<string,Blob>;onChange:(value:BookCompletion)=>void;onReplace:(file:File,name:string)=>void}){
 if(book.templateId!=='beanstalk-adventure')return null;
 const c=book.completion;
 if(!c)return <section className="ts-panel"><h2>Complete your book</h2><p>Add a front cover, title/credits page and back cover with a hidden detail and ISBN/MRP spaces. Your interior pages stay as they are.</p><button onClick={()=>onChange(defaultBookCompletion([...book.pages.map(p=>p.image),...Object.keys(images)]))}>Add covers & credits</button></section>;
 const fields=[['subtitle','Subtitle',120],['author','Author / publisher',120],['credits','Credits / edition details',800],['blurb','Back-cover blurb',450],['easterEgg','Back-cover Easter egg clue',160],['isbn','ISBN (leave blank until assigned)',40],['mrp','MRP, including currency (optional)',40]] as const;
 return <details className="ts-panel"><summary>Covers, credits & publishing details</summary><p>Reading order: front cover → title/credits → story → back cover. Use Read book to preview all pages. Copy the missing-images prompt to generate any unfinished covers using the same character designs, colours, brushwork and textures as the interior.</p><div className="ts-fields">{fields.map(([key,label,max])=><label key={key}>{label}{key==='credits'||key==='blurb'?<textarea maxLength={max} value={c[key]} onChange={e=>onChange({...c,[key]:e.target.value})}/>:<input maxLength={max} value={c[key]} onChange={e=>onChange({...c,[key]:e.target.value})}/>}</label>)}{(['frontCover','backCover'] as const).map(key=><fieldset key={key}><legend>{key==='frontCover'?'Front cover':'Back cover'} · {images[c[key].image]?'Artwork added':'Artwork pending'}</legend><label>Cover scene<textarea maxLength={2000} value={c[key].scene} onChange={e=>onChange({...c,[key]:{...c[key],scene:e.target.value}})}/></label><label>Upload square cover illustration<input type="file" accept=".png,.jpg,.jpeg,.webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)onReplace(file,c[key].image);}}/></label><p className="ts-help">{c[key].image} · 210 × 210 mm</p></fieldset>)}</div><p className="ts-help">ISBN and MRP remain editable. The barcode area is reserved blank; no barcode is invented. Keep the clue consistent with the hidden detail in your back-cover illustration.</p></details>;
}
