'use client';
import { useState } from 'react';
import { templates, type TemplateId } from '../../lib/template-book';
import { templateBlueprints, templateSize, blueprintSvg } from '../../lib/template-layouts';
import { renderLayoutSample } from '../../lib/template-layout-sample';
export default function TemplateLayoutSamples({id}:{id:TemplateId}){
 const options=templateBlueprints(id);const [selected,setSelected]=useState(0);const t=templates.find(t=>t.id===id)!;const b=options[selected]||options[0];const size=templateSize(id);
 return <div className="ts-template-layout-samples"><h3>{t.name} · inside your book</h3><p>{t.description}</p><p>Actual app layout with sample Hindi and English text. Shaded shapes reserve space for your illustrations; they are not finished artwork.</p><iframe title={`${t.name} app-rendered layout sample`} sandbox="allow-same-origin" srcDoc={renderLayoutSample(id,b.id)} style={{width:'100%',aspectRatio:`${size.width}/${size.height}`,border:0}}/><label>Compare supported arrangements<select value={b.id} onChange={e=>setSelected(options.findIndex(v=>v.id===e.target.value))}>{options.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><p>{b.intent}</p><div className="ts-sample-arrangements">{options.map((v,i)=><button key={v.id} aria-pressed={b.id===v.id} onClick={()=>setSelected(i)}><img alt={`${v.name} placement guide`} src={`data:image/svg+xml;charset=utf-8,${encodeURIComponent(blueprintSvg(v,t.paper,t.accent,1000*size.height/size.width))}`}/><span>{v.name}</span></button>)}</div><p><strong>Illustration direction:</strong> {t.art}</p><p>The website includes these arrangements and this illustration direction in your book prompt and request ZIP.</p><style>{`.ts-sample-arrangements{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:12px 0}.ts-sample-arrangements button{display:block!important;text-align:left;padding:8px!important;background:#fffdf6;border:1px solid #cbc8bb}.ts-sample-arrangements button[aria-pressed=true]{outline:2px solid #234139}.ts-sample-arrangements img{width:100%;display:block}.ts-sample-arrangements span{display:block;font-size:12px;margin-top:6px}`}</style></div>;
}
