/** Shared instructions for external image generation; this is not a job scheduler. */
export function illustrationBatchPrompt(finalZip: string, filenames?: string[], imagesOnly = false, batchSize: 4 | 10 = 10) {
  const queue = filenames ? [...new Set(filenames)] : undefined;
  const batches = queue && Array.from({ length: Math.ceil(queue.length / batchSize) }, (_, index) =>
    `Batch ${index + 1}: ${queue.slice(index * batchSize, (index + 1) * batchSize).map(name => `images/${name}`).join(', ')}`);
  return `ILLUSTRATION BATCHES — UP TO ${batchSize} PER REQUEST:
Plan the complete requested scope and lock the ordered image filenames, accompanying text and style/character guide before drawing. Do not reduce the requested total to 20 or 10. Divide the queue into consecutive batches of at most ${batchSize} illustrations: ${batchSize === 10 ? '25 images means 10 + 10 + 5; 32 means 10 + 10 + 10 + 2.' : '9 images means 4 + 4 + 1; 12 means 4 + 4 + 4.'} Reuse the same character reference and style across batches.
${queue ? `There are ${queue.length} illustrations in this generation queue and ${batches!.length} batches.\n${batches!.join('\n') || 'Nothing remains to generate. Do not create extra artwork.'}` : `Calculate the batch count as ceiling(total declared illustrations / ${batchSize}), after the complete plan is established.`}
Generate ONLY the next unfinished batch in this request, with separate image-generation calls, never a montage. Save each actual image immediately using its exact declared filename, together with its accompanying editable text. Do not regenerate completed work unless replacement was explicitly requested.
After each non-final batch, automatically create and provide Batch-01.zip, Batch-02.zip, etc., containing that batch's actual images and ${imagesOnly ? 'text-context.md with the supplied accompanying text; do not include or change book.json' : 'the full book.json manuscript'}. Include progress.json listing the full ordered queue, verified completed filenames, missing filenames and next batch, plus continuation.md containing the style guide, reference requirements and remaining scene briefs. Ask the user to download the ZIP and reply Continue. STOP until that next request; do not ask for individual scene prompts or per-image approval.
FINAL BATCH: In the same response, automatically create ${finalZip} containing ALL images across every batch in the requested scope, ${imagesOnly ? 'text-context.md and a numbered index, without including or rewriting book.json' : 'the complete book.json with all accompanying text and a numbered index'}, and the required review files. Do not wait for a separate packaging request. Include earlier completed book images when assembling a complete-book package. Preserve the established images/ paths and filenames. Open the finished ZIP and verify every declared image exists, is a readable PNG/JPEG/WebP, is nonempty, and has no duplicate destination; check text-to-image mapping before calling it complete.
RECOVERY: Check image-generation and ZIP/file tools before starting. If unavailable, explain the limitation and provide the plan/manuscript without claiming a ZIP exists. On a rate-limit or temporary tool error, stop repeated retries; if file tools still work, immediately return a clearly labelled partial ZIP and the exact resume checklist. If interrupted, missing images are allowed for recovery, never for a claim of final completion. If earlier images, source files or references are unavailable, request the previous batch ZIPs or missing attachments before proceeding; never silently omit or recreate them. No fake download links or placeholders. Saved checkpoints help recovery but cannot prevent server errors or guarantee a final checkpoint if the conversation becomes inaccessible.`;
}
