/** Original editable directions inspired by the credited covers, not reproductions. */
export const literaryTemplates = [
 {id:'manifesto',name:'The bold edition',description:'Oversized serif cover. A bold opening passage faces a spare illustrated page.',paper:'#f1ce64',ink:'#211f18',accent:'#694614',art:'Expressive black ink linework on flat ochre paper. One isolated narrative object, generous unmarked space, no lettering.',demo:'/pilot/gita/composite.jpg',reference:'Martyr!',designer:'Linda Huang',sampleTitle:'The art of courage'},
 {id:'wild',name:'The living atlas',description:'A dark botanical cover opens into a luminous specimen plate and field notes.',paper:'#17231f',ink:'#f4edce',accent:'#c0d7a3',art:'Original natural-history engraving and opaque gouache, intricate botanical specimens on charcoal green, sage, turquoise, ivory and restrained vermilion. No lettering.',demo:'/templates/living-atlas.png',reference:'Southern Reach series',designer:'Pablo Delcan',sampleTitle:'A world within'},
 {id:'fragments',name:'The memory archive',description:'Cut-paper imagery and a circular title seal. Inside, a collage plate faces annotated prose.',paper:'#eae3d4',ink:'#273c43',accent:'#973e2d',art:'Original archival collage of architectural details and objects, halftone textures, rust-red paper fragments and blue-black ink. No fabricated archival evidence or lettering.',demo:'/pilot/gita/lamp.jpg',reference:'The Memory Police',designer:'Tyler Comrie',sampleTitle:'Objects of memory'},
 {id:'chromatic',name:'The color story',description:'Overlapping color fields frame the title. Inside, a sculptural chapter opening faces a reading page.',paper:'#f6e3cc',ink:'#282344',accent:'#7f302a',art:'Abstract cut-paper composition of broad organic forms in cobalt, coral, rose and deep green, balanced negative space, no lettering.',demo:'/pilot/gita/composite.jpg',reference:'The Vanishing Half',designer:'Lauren Peters-Collaer',sampleTitle:'Many ways of seeing'},
 {id:'echo',name:'The word edition',description:'Repeated words make the cover. Spacious poetry and a typographic margin continue the rhythm inside.',paper:'#14191f',ink:'#e9d98c',accent:'#b0c7eb',art:'Minimal monochrome ink mark or single small still-life vignette. Typography is supplied by the layout; do not generate letters in artwork.',demo:'/pilot/gita/lamp.jpg',reference:'I Remember',designer:'David Pearson',sampleTitle:'What we carry'},
 {id:'haze',name:'The quiet atmosphere',description:'A soft-focus color field and low-set title. Two airy reading pages leave room for reflection.',paper:'#efe0d7',ink:'#513d36',accent:'#785143',art:'Soft-focus atmospheric watercolor, a single diffused terracotta form on blush paper, tactile grain and large quiet spaces. No lettering.',demo:'/pilot/gita/journey.jpg',reference:'The Nursery',designer:'Linda Huang',sampleTitle:'The space between'},
] as const;
export const literaryReferenceUrl='https://lithub.com/the-best-book-covers-of-the-last-decade/';
export function isLiteraryTemplate(id:string){return literaryTemplates.some(t=>t.id===id);}
const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function literaryCover(id:string,title:string,language:string,image?:string){
 const t=literaryTemplates.find(t=>t.id===id);
 if(!t)return '';
 return `<section class="spread cover ${id} literary-cover"><div class="cover-visual" aria-hidden="true">${image?`<img src="${escapeHtml(image)}" alt="">`:''}<i></i><b></b></div>${id==='echo'?`<div class="cover-echo" aria-hidden="true">${Array.from({length:5},()=>`<span>${escapeHtml(title)}</span>`).join('')}</div>`:''}<small class="cover-kicker">AN ILLUSTRATED READING EDITION</small><h1>${escapeHtml(title)}</h1><p class="cover-language">${escapeHtml(language)}</p><small class="cover-footer">IKS BOOK STUDIO</small></section>`;
}
export function literaryCss(){return `
/* Shared by template samples, the live editor, and exported books. */
.literary-cover{position:relative;isolation:isolate;overflow:hidden!important;container-type:inline-size;border:0!important;box-shadow:none!important;text-align:left!important;padding:8%!important;align-items:flex-start!important;justify-content:flex-start!important;width:210mm}
.literary-cover h1{position:relative;z-index:2;font-family:Georgia,serif;font-size:15cqw!important;line-height:.94;letter-spacing:-.065em;max-width:100%!important;margin:12% 0 0;overflow-wrap:anywhere}
.literary-cover small{color:inherit;font:2.4cqw Arial,sans-serif;letter-spacing:.14em;z-index:2}.literary-cover .cover-language{font:3cqw/1.4 Arial,sans-serif;z-index:2;max-width:85%}.literary-cover .cover-footer{position:absolute;bottom:6%;left:8%}.cover-visual{position:absolute;inset:0;z-index:-1}.cover-visual img{width:100%;height:100%;object-fit:cover}.cover-visual i,.cover-visual b{position:absolute;display:block}
.manifesto.literary-cover h1{font-weight:900;font-size:18cqw!important}.manifesto .cover-visual{inset:50% 8% 14% 45%;transform:rotate(-8deg)}.manifesto .cover-visual img{mix-blend-mode:multiply;filter:grayscale(1) contrast(1.4);object-fit:contain}.manifesto .copy{justify-content:flex-start;padding:7% 6%;border-right:1px solid #694614}.manifesto .copy h2{font:700 2.8em/.95 Georgia,serif;letter-spacing:-.05em;color:#211f18}.manifesto .meaning{border-top:2px solid #211f18;padding-top:6%}.manifesto .art{padding:12% 7%}.manifesto .art img{filter:grayscale(1);mix-blend-mode:multiply}
.wild.literary-cover h1{font-family:Arial,sans-serif;font-size:11cqw!important;letter-spacing:-.04em;max-width:80%!important}.wild .cover-visual{inset:26% 5% 8%}.wild .cover-visual img{object-fit:contain}.wild .cover-language{max-width:55%}.wild .copy{order:2;width:43%;padding:6% 5%;background:#ede9d9;color:#26382c}.wild .copy h2{color:#354c38;text-transform:uppercase;letter-spacing:.14em}.wild .art{width:57%;padding:3%}.wild .art img{height:100%;object-fit:contain}.wild .meaning{color:#354c38}.wild .folio{left:auto;right:5%;color:#354c38}
.fragments.literary-cover .cover-visual{inset:0}.fragments .cover-visual img{filter:grayscale(1) contrast(1.35);mix-blend-mode:multiply;object-fit:cover;transform:scale(1.12)}.fragments .cover-visual i{inset:5% 65% 45% -8%;background:#a4442f;transform:rotate(25deg)}.fragments .cover-visual b{inset:65% -10% 6% 48%;background:#edcc93;transform:rotate(-20deg)}.fragments.literary-cover h1{position:absolute;top:13%;right:7%;margin:0;width:60%;aspect-ratio:1;border:3px double #273c43;border-radius:50%;background:#eae3d4;display:flex;align-items:center;justify-content:center;text-align:center;padding:9%;font-size:8.5cqw!important;letter-spacing:-.04em}.fragments .cover-kicker{background:#eae3d4;padding:2%;font-size:2cqw}.fragments .cover-language{position:absolute;bottom:12%;background:#eae3d4;padding:2%}.fragments .cover-footer{background:#eae3d4;padding:1%}.fragments .art{order:-1;background:#b65b43;width:46%;padding:7%;transform:rotate(-2deg) scale(.88)}.fragments .art img{filter:grayscale(1);border:8px solid #eae3d4}.fragments .copy{width:54%;padding:6%}.fragments .copy h2{border-bottom:3px double #973e2d;padding-bottom:5%;font-variant:small-caps}.fragments .meaning{border-left:3px solid #973e2d;padding-left:6%}
.chromatic .cover-visual{background:#eaa9c8}.chromatic .cover-visual img{display:none}.chromatic .cover-visual:before{content:'';position:absolute;inset:15% -25% -8% 25%;background:#263eb4;border-radius:48% 12% 35% 50%;transform:rotate(24deg)}.chromatic .cover-visual i{inset:40% 25% -20% -25%;background:#dc5736;border-radius:50%;transform:rotate(-35deg)}.chromatic .cover-visual b{inset:-25% -20% 60% 40%;background:#244b3b;border-radius:45%}.chromatic.literary-cover{color:#fff1d9}.chromatic.literary-cover h1{font-family:Arial,sans-serif;text-transform:uppercase;font-weight:900;font-size:15cqw!important;line-height:1.03;letter-spacing:-.05em;max-width:90%!important;text-shadow:0 1px 2px #0003;margin-top:30%}.chromatic .cover-kicker{background:#282344;padding:2%}.chromatic .cover-footer{background:#282344;padding:2%}.chromatic .copy{position:relative;width:100%;padding:6% 7% 6% 57%;background:linear-gradient(90deg,#263eb4 0 50%,#f6e3cc 50%);justify-content:center}.chromatic .copy h2{position:absolute;left:6%;top:13%;width:37%;color:#fff1d9;font:700 3.1em/1.03 Arial,sans-serif;letter-spacing:-.06em}.chromatic .copy:before{content:'';position:absolute;width:29%;height:24%;left:10%;bottom:10%;border-radius:50% 30% 50% 10%;background:#eaa9c8;transform:rotate(-20deg)}.chromatic .art{display:none}.chromatic .meaning{color:#513a51}
.echo.literary-cover h1{font-family:Arial,sans-serif;font-size:8cqw!important;letter-spacing:0;position:absolute;bottom:15%;margin:0;max-width:80%!important;color:#b0c7eb}.echo .cover-visual{display:none}.cover-echo{position:absolute;inset:12% 8% 31%;display:flex;flex-direction:column;justify-content:space-between;overflow:hidden}.cover-echo span{font:5.5cqw/1.2 monospace;text-transform:uppercase;letter-spacing:.22em}.cover-echo span:nth-child(2n){opacity:.3;transform:translateX(12%)}.echo .cover-language{position:absolute;bottom:9%;margin:0;font-size:2.5cqw}.echo .copy{width:100%;padding:8% 15% 8% 28%;text-align:left;position:relative}.echo .copy:before{content:'READ / REFLECT / RETURN';position:absolute;left:7%;top:12%;writing-mode:vertical-rl;letter-spacing:.35em;font: .8em monospace;color:#b0c7eb}.echo .copy h2{color:#b0c7eb;letter-spacing:.15em;text-transform:uppercase}.echo .original{font-size:1.6em;line-height:1.9}.echo .meaning{border-top:1px solid #b0c7eb;padding-top:5%;max-width:75%;color:#e9d98c}.echo .art{display:none}
.haze .cover-visual{background:radial-gradient(ellipse at 48% 38%,#c08365 0%,#d4a68d 15%,#efe0d7 43%)}.haze .cover-visual img{display:none}.haze.literary-cover h1{position:absolute;bottom:15%;left:8%;font-size:12cqw!important;font-weight:400;max-width:82%!important;line-height:1.1;letter-spacing:-.055em}.haze .cover-language{position:absolute;bottom:9%;margin:0}.haze .copy{width:100%;display:grid;grid-template-columns:1fr 1fr;column-gap:18%;align-content:center;padding:9%;position:relative;background:radial-gradient(ellipse at 90% 5%,#d8ae9733,transparent 40%)}.haze .copy h2{grid-column:1/-1;font-weight:400;letter-spacing:.08em;margin-bottom:7%;color:#785143}.haze .meaning{margin:0;color:#513d36}.haze .art{display:none}
`}
