import type { Blueprint, Region } from './template-layouts.ts';
type Box=[number,number,number,number];
export type ReferenceContract={coverage:string; ratio:number; art:string; typography:string; sans?:boolean; centered?:boolean; layouts:Blueprint[]};
const r=([x,y,w,h]:Box):Region=>({x,y,w,h});
function spread(id:string,name:string,referenceIndex:number,art:Box[],text:Box[],intent:string,coloured=false):Blueprint {
 return {id:`reference-${id}`,name,referenceIndex,intent,art:art.map(r),original:text.slice(0,-1).map(r),meaning:r(text[text.length-1]),integrated:true,coloured};
}
const observed='Interior composition observed in the reference. Coordinates are measured approximations; text length may require additional spreads. Original font identity is unverified.';
const artOnly='Artwork reference only: illustration placement follows the reference; editable text placement is an app adaptation because no interior lettering is visible.';
export const referenceContracts:Record<string,ReferenceContract>={
 'beanstalk-adventure':{coverage:observed,ratio:2,art:'Flat textured gouache and cut-paper shapes; expressive angular faces, slim limbs, sparse facial marks and playful perspective. Teal/navy foliage, mustard and ochre architecture, russet accents, pale cream sky. Dry-brush grain, minimal modelling. Avoid realistic devotional/calendar painting, glossy jewels, cinematic light, dense foliage around text, low-poly faceting and a repeated giant standing figure.',typography:'Small dark warm serif narration, larger italic serif dialogue; left aligned; generous leading, no boxed captions.',layouts:[
 spread('beanstalk-opening','Low landscape and upper-right encounter',1,[[0,65,100,35],[56,0,44,65]],[[13,12,30,35],[77,67,20,15]],'Low landscape anchors the spread. Upper-right encounter; passage in open upper-left sky, reflection below the encounter.'),
 spread('beanstalk-diagonal','Two diagonal story moments',2,[[0,0,55,64],[70,20,30,80],[29,72,41,28]],[[3,73,24,23],[59,7,31,27],[55,51,14,18]],'Exactly TWO narrative scenes: upper-left establishing scene and lower-right interaction. The two lower/right art regions form one connected scene. Three separate reading islands follow the reference.'),
 spread('beanstalk-landscape','Tall left figure and open central sky',3,[[0,55,100,45],[10,0,35,65],[78,15,22,65]],[[55,10,21,19],[55,31,21,18]],'Continuous landscape with a tall left figure and right architecture. Both passages share the open upper-centre sky.') ]},
 'bedtime-skies':{coverage:observed,ratio:1400/995,sans:true,centered:true,art:'Flat textured turquoise/cyan water, coral and yellow ochre, magenta goggles. Thin rough dark outlines; large white oval eyes and dark pupils, round curly hair, oversized heads and slender limbs. Friendly expressive cartoon gestures; no realistic skin or glossy 3D shading.',typography:'Compact rounded sans-serif, centred paragraphs, normal upright explanation, dark grey on white.',layouts:[
 spread('ocean-bottom','Ocean above a narrow white reading band',0,[[0,0,100,80]],[[16,83,68,7],[16,91,68,7]],'Art occupies the upper 80%; both passages stack in the bottom white band.'),
 spread('ocean-left','Underwater scene with white left passage',1,[[37,0,63,100]],[[6,36,28,17],[6,55,28,15]],'Organic underwater edge at the right of a narrow white left reading area.'),
 spread('ocean-top','Open upper text above water',2,[[0,35,100,65]],[[19,9,63,12],[19,23,63,10]],'Short centred passages above the lower water scene.') ]},
 'paper-play':{coverage:observed,ratio:500/306,art:'Warm olive and gold, dusty blue, softly modelled gouache; expressive large heads and slim fairy-tale figures with soft dark contours. Full-page left illustration; delicate pale-gold rectangular frame with corner flourishes on the right.',typography:'Small warm-black serif body within ONE right-page gold frame; restrained gold italic heading and drop-cap character when supplied.',layouts:[spread('fairytale-frame','Left illustration facing one framed reading page',0,[[0,0,50,100]],[[62,36,26,24],[62,63,26,20]],'Full-bleed left illustration; one fine gold frame x57 y10 width36 height80 around the right reading page. Never frame each paragraph separately.')]},
 'snowy-friends':{coverage:observed,ratio:2,sans:true,art:'Dense coloured-pencil and charcoal grain; directional hatching in fur, simple long wolf snout, broad bear silhouette and tiny warm almond eyes. Quiet grey, charcoal, white and lavender-blue landscapes. Avoid clean vector edges, shiny fur or saturated rainbow colour.',typography:'Small upright sans-serif, left-aligned passages in two columns beneath art, generous white margins.',layouts:[spread('snow-band','Wide pencil scene and narrow white band',0,[[0,0,100,82]],[[5,86,39,11],[56,86,39,11]],'Landscape covers upper82%; two small reading blocks below.'),spread('snow-close','Close encounter above deeper reading band',1,[[0,0,100,76]],[[5,81,39,15],[56,81,39,15]],'Closer characters above a24% white reading band.')]},
 'bedtime-play':{coverage:observed,ratio:1.411,sans:true,art:'Loose black ink and crayon outlines; wobbly perspective, playful elongated or distorted limbs and noses, minimal facial marks. Bold flat coral, mustard, purple, teal and green; visible hand-drawn scuffs. Text sits directly over quiet coloured scene areas, never an added cream inset.',typography:'Small upright dark sans-serif on quiet flat background colour, left aligned.',layouts:[spread('bo-floor','Room with lower-right floor text',0,[[0,0,69,100],[69,0,31,80]],[[73,82,24,8],[73,91,24,7]],'Full room; reserve pale floor at lower right for two short passages.',true),spread('bo-green','Room with upper-left green text area',1,[[0,30,100,70],[40,0,60,30]],[[8,7,29,10],[8,19,29,9]],'Text occupies the flat green upper-left wall; action fills lower and right areas.',true),spread('bo-parrot','Diagonal action with two coloured reading gaps',2,[[40,0,40,100],[0,0,27,100]],[[28,59,12,25],[81,43,17,20]],'Large diagonal central figure; small passage left of centre and reflection at right, directly on coral.',true)]},
 'treehouse-days':{coverage:observed,ratio:1.6,art:'Very light scratchy sepia/black pen and coloured pencil, transparent watercolour washes with abundant white paper. Tiny long-nosed expressive figures and fine twig detail; loose observational nature drawings. Avoid dense opaque paintings, heavy outlines or rectangular panels.',typography:'Small gentle serif text between sketches; left aligned, upright body and explanation.',layouts:[spread('tree-four','Four nature vignettes and captions',1,[[0,8,48,35],[52,6,48,37],[0,54,48,35],[52,54,48,35]],[[5,44,40,9],[55,44,40,9],[5,90,40,9],[55,90,40,9]],'Four distinct moments in a2x2 arrangement, each caption below its own sketch.'),spread('tree-wind','Continuous windy scene with lower passages',2,[[0,0,100,56],[42,56,12,44]],[[4,59,36,23],[56,75,39,21]],'Airy continuous nature scene with lower-left and lower-right white reading gaps.')]},
 'colourful-journey':{coverage:observed,ratio:2,art:'Scuffed printed-paper collage, flat cut shapes, angular long limbs, tiny dark heads and exaggerated scale. Mustard, cyan, vermilion, hot pink, charcoal and ivory; visible print grain. No smooth photorealistic modelling or separate framed reading page.',typography:'Small spare black serif, left-aligned in open scene spaces.',layouts:[spread('ariba-room','Collage room with upper-left reading space',0,[[30,0,70,100],[0,48,30,52]],[[6,9,22,20],[6,31,22,14]],'Full scene with quiet upper-left paper for narration and reflection.'),spread('ariba-horizon','Low landscape beneath two upper passages',1,[[0,40,100,60],[76,30,20,70]],[[6,8,32,24],[57,8,37,21]],'Low wide landscape and right character; separate upper-left and upper-right passages.'),spread('ariba-diagonal','Diagonal collage between reading islands',2,[[28,0,45,66],[46,65,54,35]],[[3,36,23,27],[8,69,36,24],[75,8,22,23]],'Diagonal creature/action with left, lower-left and upper-right text islands.')]},
 'painted-memories':{coverage:observed,ratio:2.448,sans:true,art:'Oil-pastel/gouache canvas grain, hazy edges, dreamlike oversized objects, long strangely proportioned figures and tiny minimal faces. Ultramarine, ochre, burnt orange and soft cream. Avoid crisp vector cartoons or decorative borders.',typography:'Compact upright rounded sans-serif; small paragraph group vertically centred on a white right page.',layouts:[spread('memories-facing','Full left painting and quiet right page',0,[[0,0,50,100]],[[58,36,34,17],[58,56,34,15]],'Painting fills the left half; a small centred-height reading group occupies the right white half.'),spread('memories-full','Full painting with small lower-left caption',2,[[0,0,100,84],[48,84,52,16]],[[23,85,23,6],[23,93,23,6]],'Continuous painting across spread; two very short caption lines in a pale lower-left patch.')]},
 'little-explorers':{coverage:artOnly,ratio:1400/871,art:'Flat gouache grain, copper-brown arching tree, scalloped lime and moss-green canopy, pale blue sky, rolling green ground and white foreground flowers. Expressive cartoon woodland animals, outlined slim limbs and graphic leaf shapes. Keep the broad left sky clearing and dominant right tree.',typography:'App adaptation: small dark serif text in the left sky opening; original interior font unknown.',layouts:[spread('woodland-clearing','Arching tree and left sky clearing',1,[[45,0,55,100],[0,0,45,18],[0,71,45,29]],[[5,24,34,24],[5,51,34,16]],'Follow the illustrated tree arch and left opening. Added editable passages sit within that opening.')]},
 'flower-festival':{coverage:artOnly,ratio:1400/883,art:'Soft dry-brush grain, warm peach, rose, sage and marigold. Lively large almond-shaped dark eyes, gently modelled cartoon features, rounded organic vignette boundaries fading into white. Intimate Indian family gestures and craft details; no ornate devotional poster rendering.',typography:'App adaptation: small dark serif body in existing white space; original font unavailable.',layouts:[spread('flowers-bottom','Family-room vignette above white text',0,[[0,0,100,75]],[[8,80,40,16],[55,80,37,16]],'Broad room vignette ends organically above a white bottom reading strip.'),spread('flowers-top','Low family scene beneath open text',1,[[0,30,100,70]],[[8,5,40,20],[55,5,37,20]],'Family and craft objects fill lower scene; text occupies original upper white area.'),spread('flowers-pair','Two connected craft vignettes',3,[[8,18,53,65],[65,25,27,57]],[[8,85,43,13],[57,85,35,13]],'Large left craft moment and smaller right mirror moment, with short captions in lower white space.')]},
};
export function referenceCoverage(id:string){return referenceContracts[id]?.coverage||(['manifesto','wild','fragments','chromatic','echo','haze'].includes(id)?'Cover-inspired app interior. The source does not establish interior placement or typography; this sample is the authoritative app layout, not a reproduction of an unseen interior.':'Original app-designed template. This sample defines the supported layout.');}
export function referenceStylePrompt(id:string){const p=referenceContracts[id];return `${referenceCoverage(id)}\n${p?`ILLUSTRATION AND CHARACTERS: ${p.art}\nTYPOGRAPHY: ${p.typography}\n` : ''}REFERENCE PRIORITY: Adapt the new subject into the selected template’s visual language. A devotional subject must not switch the medium to calendar art. Character sheets must use this template’s shape language, texture and palette; regenerate a mismatched sheet before continuing. Do not mirror layouts, invent panels or relocate text for variety. Repeating an observed arrangement is allowed. Original wording stays intact; split long passages into more spreads instead of enlarging text regions or shrinking type.`;}

/** Page-paper and reading-ink approximations; art palette is specified separately above. */
export function referencePalette(id:string,fallback:{paper:string;ink:string;accent:string}){
 if(!referenceContracts[id])return fallback;
 return {...fallback,paper:['beanstalk-adventure','colourful-journey'].includes(id)?'#fffbed':'#ffffff',ink:'#292723'};
}
