/** Cached catalogue previews for reliable generation packages. See public/templates/references/ATTRIBUTION.json. */
export const referenceAssets:Record<string,string> = {
 "iks-notes:0":"/templates/references/iks-notes/reference-1.jpg",
 "iks-notes:1":"/templates/references/iks-notes/reference-2.jpg",
  "little-explorers:0": "/templates/references/little-explorers-1.webp",
  "little-explorers:1": "/templates/references/little-explorers-2.webp",
  "bedtime-skies:0": "/templates/references/bedtime-skies-1.webp",
  "bedtime-skies:1": "/templates/references/bedtime-skies-2.webp",
  "bedtime-skies:2": "/templates/references/bedtime-skies-3.webp",
  "paper-play:0": "/templates/references/paper-play-1.jpg",
  "beanstalk-adventure:0": "/templates/references/beanstalk-adventure-1.webp",
  "beanstalk-adventure:1": "/templates/references/beanstalk-adventure-2.webp",
  "beanstalk-adventure:2": "/templates/references/beanstalk-adventure-3.webp",
  "beanstalk-adventure:3": "/templates/references/beanstalk-adventure-4.webp",
  "flower-festival:0": "/templates/references/flower-festival-1.webp",
  "flower-festival:1": "/templates/references/flower-festival-2.webp",
  "flower-festival:2": "/templates/references/flower-festival-3.webp",
  "flower-festival:3": "/templates/references/flower-festival-4.webp",
  "snowy-friends:0": "/templates/references/snowy-friends-1.webp",
  "snowy-friends:1": "/templates/references/snowy-friends-2.webp",
  "snowy-friends:2": "/templates/references/snowy-friends-3.webp",
  "bedtime-play:0": "/templates/references/bedtime-play-1.webp",
  "bedtime-play:1": "/templates/references/bedtime-play-2.webp",
  "bedtime-play:2": "/templates/references/bedtime-play-3.webp",
  "treehouse-days:0": "/templates/references/treehouse-days-1.webp",
  "treehouse-days:1": "/templates/references/treehouse-days-2.webp",
  "treehouse-days:2": "/templates/references/treehouse-days-3.webp",
  "colourful-journey:0": "/templates/references/colourful-journey-1.webp",
  "colourful-journey:1": "/templates/references/colourful-journey-2.webp",
  "colourful-journey:2": "/templates/references/colourful-journey-3.webp",
  "painted-memories:0": "/templates/references/painted-memories-1.webp",
  "painted-memories:1": "/templates/references/painted-memories-2.webp",
  "painted-memories:2": "/templates/references/painted-memories-3.webp"
};
